kind: Secret
apiVersion: v1
metadata:
  name: hive-database-password
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if eq .Values.database.type "internal" }}
  databasePassword: {{ .Values.database.internal.databasePassword | default "not_set" | b64enc }}
  {{- if .Values.database.internal.databaseAdminPassword }}
  databaseAdminPassword: {{ .Values.database.internal.databaseAdminPassword | b64enc }}
  {{- end }}
  {{- end }}
  {{- if eq .Values.database.type "external" }}
  databasePassword: {{ .Values.database.external.password | default "not_set" | b64enc }}
  {{- end }}
