apiVersion: v1
kind: Secret
metadata:
  name: airflow-ssh-secret
  namespace: airflow
data:
  gitSshKey: LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0NCmIzQmxibk56YUMxclpYa3RkakVBQUFBQUJHNXZibVVBQUFBRWJtOXVaUUFBQUFBQUFBQUJBQUFBTXdBQUFBdHpjMmd0WlcNClF5TlRVeE9RQUFBQ0Rqc3dFc1NvdFFXb1I1LzFyb01ITlRRdVNKV0Q2R09uVnl2MFpJakdqdjNBQUFBSmdhcXd3ckdxc00NCkt3QUFBQXR6YzJndFpXUXlOVFV4T1FBQUFDRGpzd0VzU290UVdvUjUvMXJvTUhOVFF1U0pXRDZHT25WeXYwWklqR2p2M0ENCkFBQUVBeityVnZYejNFYnR4VXFhS2JRMmlxc3pLYms1Y2JjL1paUlc0MFpET3lFZU96QVN4S2kxQmFoSG4vV3Vnd2MxTkMNCjVJbFlQb1k2ZFhLL1JraU1hTy9jQUFBQUZXRnVaSEpsYVdOb2FYSnZRR2R0WVdsc0xtTnZiUT09DQotLS0tLUVORCBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0=