{{- if eq .Values.expose.type "loadBalancer" }}
{{- $loadBalancer := .Values.expose.loadBalancer }}

# ------------------------------------------------------------------------------
# Hive Service using LoadBalancer
# ------------------------------------------------------------------------------

apiVersion: v1
kind: Service
metadata:
  name: {{ $loadBalancer.name }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
    role: hive
  {{- if $loadBalancer.annotations }}
  {{- with $loadBalancer.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
spec:
  type: LoadBalancer
  {{- with $loadBalancer.sourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if $loadBalancer.IP }}
  loadBalancerIP: {{ $loadBalancer.IP }}
  {{- end }}
  ports:
    - name: http
      port: {{ $loadBalancer.ports.http.port }}
      targetPort: 9083
  selector:
    {{- include "app.labels" . | nindent 4 }}
    role: hive
{{- end }}
