apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apache-airflow
  namespace: argocd
  
spec:
  project: default
  source:
    repoURL: https://github.com/apache/airflow.git
    targetRevision: HEAD
    path: chart/
  destination:
    server: https://kubernetes.default.svc
    namespace: airflow

