apiVersion: v1
kind: Service
metadata:
  name: airflow-elb-webserver
  namespace: airflow
  labels:
    component: webserver
    release: airflow
  annotations:
spec:
  selector:
    component: webserver
    role: webserver
    release: airflow
  ports:
    - name: web
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer